name: auto


on:
  schedule:
  - cron: "* * * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build-go
        run: |
          go env -w GO111MODULE=on
          go build main.go
      - name: issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./main
