name: auto_create

on:
  schedule:
  - cron: "30 * * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build-go
        run: |
         go get -u
         go build main.go
      - name: issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./main
